- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4870/workspace/MavenAnsible-CICD/target/MavenWebApp.war"
        dest: "/opt/tomcat/webapps/MavenWebApp.war"
        remote_src: no
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
